// Yandex base share URL used as a fallback for APKs/firmware that don't have a newer upstream source
const YANDEX = "https://disk.yandex.ru/d/SxXwb0bgy0Ll_w";
const y = (p: string) => `${YANDEX}/${p.split("/").map(encodeURIComponent).join("/")}`;

// ---------------------------------------------------------------------------
// Car models (referenced by apps and firmware)
// ---------------------------------------------------------------------------
export const carModels = [
  { id: "all", name: "All Models", nameAr: "كل الموديلات" },
  { id: "seal", name: "Seal", nameAr: "سيل" },
  { id: "dolphin", name: "Dolphin", nameAr: "دولفين" },
  { id: "atto3", name: "Atto 3 / Yuan Plus", nameAr: "أتو 3" },
  { id: "han", name: "Han EV / DM", nameAr: "هان" },
  { id: "tang", name: "Tang EV / DM", nameAr: "تانج" },
  { id: "song-plus", name: "Song Plus / Pro", nameAr: "سونج بلس" },
  { id: "shark", name: "Shark", nameAr: "شارك" },
  { id: "leopard", name: "Leopard / Denza", nameAr: "ليوبارد / دينزا" },
] as const;

export type CarModelId = (typeof carModels)[number]["id"];
const ALL_MODELS: CarModelId[] = [
  "seal",
  "dolphin",
  "atto3",
  "han",
  "tang",
  "song-plus",
  "shark",
  "leopard",
];

// ---------------------------------------------------------------------------
// App categories (used by navbar submenu + filters)
// ---------------------------------------------------------------------------
export const appCategories = [
  { id: "all", name: "All Apps", nameAr: "كل التطبيقات" },
  { id: "navigation", name: "Navigation", nameAr: "الملاحة" },
  { id: "music", name: "Music & Radio", nameAr: "الموسيقى والراديو" },
  { id: "video", name: "Video", nameAr: "الفيديو" },
  { id: "launchers", name: "Launchers & Themes", nameAr: "المشغلات والسمات" },
  { id: "tools", name: "Tools & System", nameAr: "الأدوات والنظام" },
  { id: "carplay", name: "CarPlay", nameAr: "كار بلاي" },
  { id: "communication", name: "Communication", nameAr: "التواصل" },
  { id: "beta", name: "Beta Zone", nameAr: "منطقة بيتا" },
] as const;

export type AppCategoryId = (typeof appCategories)[number]["id"];

// ---------------------------------------------------------------------------
// Apps — all entries are direct APK downloads (Play Store does not run on BYD HU)
// Links point to the newest upstream version when available, or to the Yandex
// drive mirror as a fallback.
// ---------------------------------------------------------------------------
export interface App {
  id: string;
  name: string;
  description: string;
  descriptionAr: string;
  category: AppCategoryId;
  compatibleModels: CarModelId[];
  downloadUrl: string;
  source: "Yandex" | "Upstream" | "GitHub" | "APKMirror" | "Official";
  version?: string;
  isMod?: boolean;
  isOfficial?: boolean;
  warning?: string;
  warningAr?: string;
}

export const apps: App[] = [
  // ---------------- Navigation ----------------
  {
    id: "waze",
    name: "Waze",
    description: "Community-based navigation with real-time traffic",
    descriptionAr: "ملاحة مجتمعية مع حركة المرور في الوقت الفعلي",
    category: "navigation",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://www.apkmirror.com/apk/waze/waze/",
    source: "APKMirror",
    isOfficial: true,
  },
  {
    id: "yandex-navi",
    name: "Yandex Navigator",
    description: "Offline-capable navigation popular in CIS region",
    descriptionAr: "ملاحة بدون انترنت شائعة في روسيا",
    category: "navigation",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/RuSoft/ru.yandex.yandexnavi_14.8.1_735868601.apk"),
    source: "Yandex",
    version: "14.8.1",
  },
  {
    id: "here-wego",
    name: "Nokia HERE WeGo",
    description: "Offline maps and turn-by-turn navigation",
    descriptionAr: "خرائط غير متصلة بالإنترنت وملاحة خطوة بخطوة",
    category: "navigation",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/RuSoft/Nokia HERE WeGo v. 4.6.000.apk"),
    source: "Yandex",
    version: "4.6.0",
  },
  {
    id: "baidu-carlife",
    name: "Baidu CarLife",
    description: "Chinese phone-to-car mirroring for navigation",
    descriptionAr: "عكس الهاتف للسيارة من بايدو",
    category: "navigation",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China Application/Baidu carlife.apk"),
    source: "Yandex",
  },
  {
    id: "autonavi-gaode",
    name: "AutoNavi / Gaode Map",
    description: "Chinese navigation app (BYD customized build)",
    descriptionAr: "تطبيق خرائط صيني مخصص لـ BYD",
    category: "navigation",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/AutoNavi map custom version - Tengshi v1.550.0.92.202212121451.apk"),
    source: "Yandex",
    version: "1.550.0",
  },
  {
    id: "hud-speed-pro",
    name: "HUD Speed Pro",
    description: "Heads-up display for speed and driving info",
    descriptionAr: "شاشة عرض أمامية لسرعة القيادة",
    category: "navigation",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/RuSoft/hud_speed_pro_v53_3.apk"),
    source: "Yandex",
    version: "53.3",
  },

  // ---------------- Music & Radio ----------------
  {
    id: "spotify",
    name: "Spotify",
    description: "Official Spotify music streaming client",
    descriptionAr: "عميل سبوتيفاي الرسمي لبث الموسيقى",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://www.apkmirror.com/apk/spotify-ab/spotify-music/",
    source: "APKMirror",
    isOfficial: true,
  },
  {
    id: "spotify-mod",
    name: "Spotify Premium (MOD)",
    description: "Modified Spotify with Premium features unlocked",
    descriptionAr: "سبوتيفاي معدل مع ميزات بريميوم",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/other/Spotify-v8.8.82.634-MOD-GMA-(Getmodsapk.com).apk"),
    source: "Yandex",
    version: "8.8.82.634",
    isMod: true,
    warning: "Modified APK — use at your own risk",
    warningAr: "تطبيق معدل — استخدمه على مسؤوليتك",
  },
  {
    id: "youtube-music-revanced",
    name: "YouTube Music (ReVanced)",
    description: "YouTube Music with ReVanced patches — no ads, background play",
    descriptionAr: "يوتيوب ميوزيك مع تعديلات — بدون إعلانات",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://revanced.net/download/youtube-music",
    source: "Upstream",
    isMod: true,
    warning: "Requires microG to sign in",
    warningAr: "يتطلب microG لتسجيل الدخول",
  },
  {
    id: "yandex-music",
    name: "Yandex Music (ST Mod)",
    description: "Yandex Music client with modified sign-in",
    descriptionAr: "عميل ياندكس ميوزيك معدل",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/RuSoft/Yandex.Music.ST от Vildanoff - 2022.12.2.apk"),
    source: "Yandex",
    version: "2022.12.2",
    isMod: true,
  },
  {
    id: "aimp",
    name: "AIMP Player",
    description: "Lightweight audio player for local music",
    descriptionAr: "مشغل صوتي خفيف للملفات المحلية",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/RuSoft/aimp_3.30.1240.apk"),
    source: "Yandex",
    version: "3.30.1240",
  },
  {
    id: "poweramp",
    name: "Poweramp",
    description: "Premium music player with advanced equalizer",
    descriptionAr: "مشغل موسيقى احترافي مع موازن متقدم",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://powerampapp.com/downloads/",
    source: "Official",
    isOfficial: true,
  },
  {
    id: "kuwo",
    name: "Kuwo Music",
    description: "Chinese music streaming (BYD customized build)",
    descriptionAr: "بث موسيقى صيني مخصص لـ BYD",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/Kuwo Music_10.0.7.0.apk"),
    source: "Yandex",
    version: "10.0.7",
  },
  {
    id: "kugou",
    name: "KuGou Music",
    description: "Popular Chinese music streaming service",
    descriptionAr: "خدمة بث موسيقى صينية شهيرة",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/KuGou.apk"),
    source: "Yandex",
  },
  {
    id: "pcradio",
    name: "PCRadio Premium",
    description: "Online radio streaming app",
    descriptionAr: "تطبيق راديو عبر الإنترنت",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/RuSoft/PCRadio+PREMIUM+2.7.2.2(136) (1).apk"),
    source: "Yandex",
    version: "2.7.2",
  },
  {
    id: "tunein",
    name: "TuneIn Radio",
    description: "Global radio stations streaming",
    descriptionAr: "محطات راديو عالمية",
    category: "music",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/RuSoft/TuneIn Radio+30.6.2.270789.apk"),
    source: "Yandex",
    version: "30.6.2",
  },

  // ---------------- Video ----------------
  {
    id: "youtube-revanced",
    name: "YouTube ReVanced",
    description: "Modified YouTube with ad-block, background play & SponsorBlock",
    descriptionAr: "يوتيوب معدل مع حجب إعلانات وتشغيل في الخلفية",
    category: "video",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://revanced.net/",
    source: "Upstream",
    isMod: true,
    warning: "Requires microG for Google login",
    warningAr: "يتطلب microG لتسجيل الدخول بحساب جوجل",
  },
  {
    id: "revanced-manager",
    name: "ReVanced Manager",
    description: "Official tool to build your own ReVanced apps",
    descriptionAr: "الأداة الرسمية لبناء تطبيقات ReVanced",
    category: "video",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://github.com/ReVanced/revanced-manager/releases/latest",
    source: "GitHub",
  },
  {
    id: "tencent-video",
    name: "Tencent Video TV",
    description: "Tencent video streaming (TV edition, VIP unlocked)",
    descriptionAr: "بث فيديو تنسنت — نسخة تلفزيون مع VIP",
    category: "video",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/Tencent Video TV Book Edition V-I-P Break + Solution_1.0.0.366.apk"),
    source: "Yandex",
    version: "1.0.0.366",
    isMod: true,
  },
  {
    id: "tv-home",
    name: "TV Home",
    description: "Multi-source TV streaming aggregator",
    descriptionAr: "مجمع بث تلفزيوني متعدد المصادر",
    category: "video",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/TV home 3.0_3.5.18.apk"),
    source: "Yandex",
    version: "3.5.18",
  },
  {
    id: "star-video-wallpaper",
    name: "Star Video Wallpaper",
    description: "Animated video backgrounds for the head unit",
    descriptionAr: "خلفيات فيديو متحركة لوحدة الرأس",
    category: "video",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/star video wallpaper.apk"),
    source: "Yandex",
  },

  // ---------------- Launchers & Themes ----------------
  {
    id: "carwebguru",
    name: "CarWebGuru Launcher",
    description: "Highly customizable car launcher with themes and widgets",
    descriptionAr: "مشغل سيارات قابل للتخصيص بشكل كبير",
    category: "launchers",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://www.apkmirror.com/apk/carwebguru/carwebguru-launcher/",
    source: "APKMirror",
    version: "3.5.9",
    isOfficial: true,
  },
  {
    id: "agama",
    name: "AGAMA Car Launcher",
    description: "Clean, fast car launcher with OBD & weather integration",
    descriptionAr: "مشغل سيارات نظيف وسريع مع OBD والطقس",
    category: "launchers",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://www.apkmirror.com/apk/alter-games/agama-car-launcher/",
    source: "APKMirror",
    version: "5.0.2",
    isOfficial: true,
  },
  {
    id: "byd-theme-store",
    name: "BYD Theme Store",
    description: "Ever-changing themes for the BYD head unit",
    descriptionAr: "متجر سمات متغيرة لوحدة BYD",
    category: "launchers",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/For system/BydThemeStore ever-changing themes.apk"),
    source: "Yandex",
  },
  {
    id: "dudu-autoui",
    name: "DuduAutoUi BYD",
    description: "Customized BYD UI tweaks (multiple builds)",
    descriptionAr: "تعديلات واجهة BYD",
    category: "launchers",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/DuduAutoUi BYD"),
    source: "Yandex",
  },
  {
    id: "wallpaper-apk",
    name: "Live Wallpaper",
    description: "Animated wallpaper pack for the head unit",
    descriptionAr: "حزمة خلفيات متحركة",
    category: "launchers",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/wallpaper.apk"),
    source: "Yandex",
  },

  // ---------------- Tools & System ----------------
  {
    id: "microg",
    name: "microG GmsCore",
    description: "Open-source Google Play Services replacement",
    descriptionAr: "بديل مفتوح المصدر لخدمات جوجل",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://github.com/microg/GmsCore/releases/latest",
    source: "GitHub",
    warning: "Required for ReVanced YouTube login",
    warningAr: "مطلوب لتسجيل الدخول في ReVanced YouTube",
  },
  {
    id: "aurora-store",
    name: "Aurora Store",
    description: "Anonymous Google Play Store alternative",
    descriptionAr: "بديل مجهول لمتجر جوجل بلاي",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://gitlab.com/AuroraOSS/AuroraStore/-/releases",
    source: "GitHub",
    version: "4.8.1",
  },
  {
    id: "aurora-droid",
    name: "Aurora Droid",
    description: "F-Droid alternative client for open-source apps",
    descriptionAr: "بديل F-Droid للتطبيقات مفتوحة المصدر",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/other/AuroraDroid_1.0.8.apk"),
    source: "Yandex",
    version: "1.0.8",
  },
  {
    id: "app-manager",
    name: "App Manager",
    description: "Advanced package manager with root features",
    descriptionAr: "مدير حزم متقدم مع ميزات الروت",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://github.com/MuntashirAkon/AppManager/releases/latest",
    source: "GitHub",
    version: "3.1.0",
  },
  {
    id: "xplore",
    name: "X-plore File Manager",
    description: "Dual-pane file manager, excellent for HU transfers",
    descriptionAr: "مدير ملفات مزدوج اللوحة لنقل الملفات",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/X-plore file management cracked version [4.27.65] It is best to use APP for mutual transmission between mobile phone and car.apk"),
    source: "Yandex",
    version: "4.27.65",
    isMod: true,
  },
  {
    id: "bywave",
    name: "ByWave",
    description: "BYD system tweaks and utilities",
    descriptionAr: "تعديلات وأدوات نظام BYD",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/ByWave_3.0.3.apk"),
    source: "Yandex",
    version: "3.0.3",
  },
  {
    id: "beetle-adb",
    name: "Beetle ADB",
    description: "On-device ADB shell for wireless debugging",
    descriptionAr: "قشرة ADB على الجهاز للتصحيح اللاسلكي",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/For system/Beetle ADB1.1.apk"),
    source: "Yandex",
    version: "1.1",
  },
  {
    id: "wireless-adb",
    name: "Wireless ADB Switch",
    description: "Toggle wireless ADB from the head unit",
    descriptionAr: "تفعيل ADB لاسلكي من وحدة الرأس",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/For system/wireless adb switch.apk"),
    source: "Yandex",
  },
  {
    id: "autostart-stay",
    name: "Autostart and StaY",
    description: "Keep apps running on boot and prevent auto-kill",
    descriptionAr: "إبقاء التطبيقات تعمل بعد التشغيل",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/For system/Autostart+and+StaY 4.2.1.apk"),
    source: "Yandex",
    version: "4.2.1",
  },
  {
    id: "silent-installer",
    name: "Silent Installer",
    description: "Install APKs silently via USB on Leopard / Denza",
    descriptionAr: "تثبيت صامت عبر USB على ليوبارد ودينزا",
    category: "tools",
    compatibleModels: ["leopard"],
    downloadUrl: y("Soft/other/PackageInstaller.zip"),
    source: "Yandex",
    warning: "Leopard / Denza only — requires FAT32 USB drive",
    warningAr: "فقط لليوبارد / دينزا — يتطلب USB بتنسيق FAT32",
  },
  {
    id: "byd-condition-assistant",
    name: "BYD Car Condition Assistant",
    description: "Real-time diagnostics & car status (battery, tire, etc.)",
    descriptionAr: "تشخيص وحالة السيارة في الوقت الفعلي",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/other/byd car condition assistant v1.0.7.apk"),
    source: "Yandex",
    version: "1.0.7",
  },
  {
    id: "chekzhushou",
    name: "Battery Monitor (Chekzhushou)",
    description: "12V battery health monitor for BYD",
    descriptionAr: "مراقب صحة بطارية 12V لـ BYD",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/other/chekzhushou_1032_v1.5.6.apk"),
    source: "Yandex",
    version: "1.5.6",
  },
  {
    id: "russcanner",
    name: "Russ Scanner (OBD)",
    description: "OBD-II scanner adapted for BYD",
    descriptionAr: "ماسح OBD-II مخصص لـ BYD",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/other/com.ovz.russcanner.apk"),
    source: "Yandex",
  },
  {
    id: "aida64",
    name: "AIDA64",
    description: "Hardware info and system diagnostics",
    descriptionAr: "معلومات المكونات وتشخيص النظام",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/aida64.apk"),
    source: "Yandex",
  },
  {
    id: "sd-maid",
    name: "SD Maid SE",
    description: "System cleaner to remove app residues",
    descriptionAr: "منظف نظام لإزالة بقايا التطبيقات",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://github.com/d4rken-org/sdmaid-se/releases/latest",
    source: "GitHub",
    isOfficial: true,
  },
  {
    id: "anexplorer",
    name: "AnExplorer (Automotive)",
    description: "File manager optimized for Android Automotive / BYD",
    descriptionAr: "مدير ملفات محسّن لسيارات BYD",
    category: "tools",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://anexplorer.io/device/android-automotive/byd",
    source: "Official",
    isOfficial: true,
  },

  // ---------------- CarPlay ----------------
  {
    id: "carplay-pack",
    name: "CarPlay Pack",
    description: "CarPlay enablement pack (13.5 chipset only)",
    descriptionAr: "حزمة تفعيل CarPlay (شريحة 13.5 فقط)",
    category: "carplay",
    compatibleModels: ["atto3", "dolphin", "song-plus", "han", "tang", "seal"],
    downloadUrl: y("Soft/CarPlay/Carplay.zip"),
    source: "Yandex",
    warning: "Works only on 13.5 chipset — verify your firmware first",
    warningAr: "يعمل فقط على شريحة 13.5 — تحقق من البرنامج الثابت أولاً",
  },
  {
    id: "carplay-guide",
    name: "CarPlay Instructions",
    description: "RTF guide for the CarPlay enablement pack",
    descriptionAr: "دليل RTF لحزمة تفعيل CarPlay",
    category: "carplay",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/CarPlay/Only 13.5 chipset its file CarPlay.rtf"),
    source: "Yandex",
  },

  // ---------------- Communication ----------------
  {
    id: "telegram",
    name: "Telegram",
    description: "Official Telegram messenger (latest)",
    descriptionAr: "تليجرام الرسمي (أحدث إصدار)",
    category: "communication",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://telegram.org/android/apk",
    source: "Official",
    isOfficial: true,
  },
  {
    id: "wechat-car",
    name: "WeChat (Car Edition)",
    description: "WeChat adapted for vertical car screens",
    descriptionAr: "وي تشات مخصص لشاشات السيارات",
    category: "communication",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China Application/Car WeChat - Adapt to vertical screen.apk"),
    source: "Yandex",
  },

  // ---------------- Beta Zone ----------------
  {
    id: "byd-apps-ota",
    name: "BYD Apps & OTA Channel",
    description: "Experimental builds & newest APKs (Telegram)",
    descriptionAr: "نسخ تجريبية وأحدث التطبيقات (تليجرام)",
    category: "beta",
    compatibleModels: ALL_MODELS,
    downloadUrl: "https://t.me/just_byd",
    source: "Upstream",
  },
  {
    id: "clash-beta",
    name: "Clash",
    description: "Proxy client — advanced networking tweaks",
    descriptionAr: "عميل بروكسي لتعديلات الشبكة",
    category: "beta",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/Clash.apk"),
    source: "Yandex",
    warning: "Advanced users only",
    warningAr: "للمستخدمين المتقدمين فقط",
  },
  {
    id: "forced-rotation",
    name: "Forced Rotation",
    description: "Force screen rotation for incompatible apps",
    descriptionAr: "إجبار تدوير الشاشة للتطبيقات غير المتوافقة",
    category: "beta",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Soft/China software/forced rotation.apk"),
    source: "Yandex",
  },
];

// ---------------------------------------------------------------------------
// Firmware — latest version per Dilink / car group, pulled from the Yandex drive
// ---------------------------------------------------------------------------
export interface Firmware {
  id: string;
  name: string;
  dilink: string;
  description: string;
  descriptionAr: string;
  compatibleModels: CarModelId[];
  downloadUrl: string;
  version: string;
  chipset?: string;
  releaseDate?: string;
}

export const firmwares: Firmware[] = [
  {
    id: "di1-latest",
    name: "DiLink 1.0 (VP128)",
    dilink: "DiLink 1.0",
    description: "First-generation BYD head unit firmware",
    descriptionAr: "الجيل الأول من برامج وحدات BYD",
    compatibleModels: ["han", "tang", "song-plus"],
    downloadUrl: y("Firmware Dilink/By the list/Di1/VP128_1.50.2106240.7.2107060.zip"),
    version: "1.50.2106240.7",
    chipset: "VP128",
    releaseDate: "2021-07",
  },
  {
    id: "di2-latest",
    name: "DiLink 2.1L (5.x chipset)",
    dilink: "DiLink 2.0",
    description: "Second-generation DiLink for earlier EV / DM models",
    descriptionAr: "الجيل الثاني من DiLink للموديلات الأقدم",
    compatibleModels: ["han", "tang", "song-plus"],
    downloadUrl: y("Firmware Dilink/By the list/Di2/5.x chipset/Di2.1L_canfd_with2in1_SOP_ota_5_signed_user_2211180.2211181.zip"),
    version: "2.1L OTA 5 (2211181)",
    chipset: "5.x CAN-FD",
    releaseDate: "2022-11",
  },
  {
    id: "di3-china-latest",
    name: "DiLink 3.0 China (18.x)",
    dilink: "DiLink 3.0",
    description: "Latest DiLink 3.0 for Chinese-market builds",
    descriptionAr: "أحدث DiLink 3.0 للسوق الصيني",
    compatibleModels: ["atto3", "dolphin", "song-plus", "han", "tang"],
    downloadUrl: y("Firmware Dilink/By the list/Di3/18.x chipset/Di3.0_1for2_18.1.2.2507160.1_0 (1).zip"),
    version: "18.1.2.2507160",
    chipset: "18.x",
    releaseDate: "2025-07",
  },
  {
    id: "di3-global-1332",
    name: "DiLink 3.0 Global — Atto 3, Dolphin, Song Plus",
    dilink: "DiLink 3.0 Global",
    description: "Global OTA for Atto 3, Dolphin, Song Plus DM-i, Chazor, Seagull",
    descriptionAr: "تحديث عالمي لـ أتو 3، دولفين، سونج بلس، تشازور، سيغول",
    compatibleModels: ["atto3", "dolphin", "song-plus"],
    downloadUrl: y("Firmware Dilink/By the list/Global, OTA/13.1.32/13.1.32.2408230 Song Plus Dm-i, Chazor, Atto3, Seagull, Dolphin/Di3.0_13.1.32.2408230.zip"),
    version: "13.1.32.2408230",
    chipset: "13.x Global",
    releaseDate: "2024-08",
  },
  {
    id: "di3-global-1333",
    name: "DiLink 3.0 Global — Han, Tang, Seal, Song Pro",
    dilink: "DiLink 3.0 Global",
    description: "Global OTA for Song Plus Champion, Song Pro, Han, Tang, Seal",
    descriptionAr: "تحديث عالمي لـ سونج بلس، سونج برو، هان، تانج، سيل",
    compatibleModels: ["han", "tang", "seal", "song-plus"],
    downloadUrl: y("Firmware Dilink/By the list/Global, OTA/13.1.33/13.1.33.2412190.1.18.3.5.2411180.2 Song Plus Champion Dm-i; Song Plus EV; Song Pro; Han; Tang; Seal/Di3.0_13.1.33.2412190.1.18.3.5.2411180.2.zip"),
    version: "13.1.33.2412190",
    chipset: "13.x Global",
    releaseDate: "2024-12",
  },
  {
    id: "di4-latest",
    name: "DiLink 4.0 (21.x chipset)",
    dilink: "DiLink 4.0",
    description: "Latest DiLink 4.0 firmware for Han/Tang/Seal line",
    descriptionAr: "أحدث DiLink 4.0 لخط هان، تانج، سيل",
    compatibleModels: ["han", "tang", "seal"],
    downloadUrl: y("Firmware Dilink/By the list/Di4/21.x chipset/Di4.0_1for2_21.1.2.2511200.1_0.zip"),
    version: "21.1.2.2511200",
    chipset: "21.x",
    releaseDate: "2025-11",
  },
  {
    id: "di5-latest",
    name: "DiLink 5.0 Global (51.x)",
    dilink: "DiLink 5.0",
    description: "Global DiLink 5.0 firmware (tar package)",
    descriptionAr: "برنامج DiLink 5.0 العالمي",
    compatibleModels: ["seal", "han", "tang"],
    downloadUrl: y("Firmware Dilink/By the list/Di5/Di5.0_23.1.4.2506089.1_0.zip"),
    version: "23.1.4.2506089",
    chipset: "23.x",
    releaseDate: "2025-06",
  },
  {
    id: "di51-latest",
    name: "DiLink 5.1 (34.1.31)",
    dilink: "DiLink 5.1",
    description: "Latest DiLink 5.1 firmware for next-gen models",
    descriptionAr: "أحدث DiLink 5.1 للموديلات الجديدة",
    compatibleModels: ["seal", "han", "tang", "shark"],
    downloadUrl: y("Firmware Dilink/By the list/Di5.1/34.1.31/YDRAY-Di5.1_34.1.31.2511244.1.34.2.3.2511224.2.zip"),
    version: "34.1.31.2511244",
    chipset: "34.x",
    releaseDate: "2025-11",
  },
  {
    id: "di51-leopard",
    name: "DiLink 5.1 — Leopard 8",
    dilink: "DiLink 5.1",
    description: "Dedicated firmware for Leopard 8",
    descriptionAr: "برنامج مخصص لليوبارد 8",
    compatibleModels: ["leopard"],
    downloadUrl: y("Firmware Dilink/By the list/Di5.1/Leopard 8"),
    version: "Leopard 8 folder",
    chipset: "34.x",
  },
  {
    id: "di6-latest",
    name: "DiLink 6.0 (31.1.16)",
    dilink: "DiLink 6.0",
    description: "Latest DiLink 6.0 firmware",
    descriptionAr: "أحدث DiLink 6.0",
    compatibleModels: ["seal", "han", "tang", "shark"],
    downloadUrl: y("Firmware Dilink/By the list/Di6/31.1.16/Di6_31.1.16.2412160.1.31.2.4.2412160.2.zip"),
    version: "31.1.16.2412160",
    chipset: "31.x",
    releaseDate: "2024-12",
  },
  {
    id: "di300-latest",
    name: "DiLink 300 (41.1.2)",
    dilink: "DiLink 300",
    description: "Premium-tier DiLink firmware (Denza / Yangwang)",
    descriptionAr: "برنامج DiLink 300 (دينزا / يانغوانغ)",
    compatibleModels: ["leopard"],
    downloadUrl: y("Firmware Dilink/By the list/Di300/Di300_41.1.2.2507218.1_0.zip"),
    version: "41.1.2.2507218",
    chipset: "41.x",
    releaseDate: "2025-07",
  },
  {
    id: "upgrade-assistant",
    name: "DiLink Upgrade Assistant",
    dilink: "Tool",
    description: "Offline tool to obtain the upgrade verification code",
    descriptionAr: "أداة للحصول على رمز التحقق بدون انترنت",
    compatibleModels: ALL_MODELS,
    downloadUrl: y("Firmware Dilink/DiLink Upgrade Assistant (Offline Obtain Verification Code).apk"),
    version: "Assistant",
  },
];

// ---------------------------------------------------------------------------
// Community
// ---------------------------------------------------------------------------
export interface CommunityLink {
  id: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  platform: "telegram" | "youtube" | "facebook" | "whatsapp" | "forum" | "website";
  url: string;
  members?: string;
  region?: string;
}

export const communityLinks: CommunityLink[] = [
  {
    id: "byd-apps-ota",
    name: "BYD Apps & OTA",
    nameAr: "تطبيقات وتحديثات BYD",
    description: "Main hub — apps, firmware and everything useful for BYD",
    descriptionAr: "المركز الرئيسي للتطبيقات والبرامج الثابتة",
    platform: "telegram",
    url: "https://t.me/just_byd",
    members: "21,000+",
    region: "Global",
  },
  {
    id: "byd-ota-group",
    name: "BYD OTA Discussion",
    nameAr: "نقاش تحديثات BYD",
    description: "Discussion group focused on OTA updates",
    descriptionAr: "مجموعة نقاش حول تحديثات OTA",
    platform: "telegram",
    url: "https://t.me/byd_ota",
    region: "Global",
  },
  {
    id: "byd-chat",
    name: "BYD Chat",
    nameAr: "دردشة BYD",
    description: "Owners of Han, Tang, Song, Seal, Dolphin — chat & tips",
    descriptionAr: "مجتمع لملاك هان، تانج، سونج، سيل، دولفين",
    platform: "telegram",
    url: "https://t.me/bydchat",
    members: "3,000+",
    region: "Global",
  },
  {
    id: "club-byd",
    name: "Club BYD",
    nameAr: "نادي BYD",
    description: "EV enthusiasts community — sustainable mobility",
    descriptionAr: "مجتمع عشاق السيارات الكهربائية",
    platform: "telegram",
    url: "https://t.me/ClubBYD",
    region: "Global",
  },
  {
    id: "byd-ev-jordan",
    name: "BYD EV Club Jordan",
    nameAr: "نادي BYD الأردن",
    description: "BYD community in Jordan",
    descriptionAr: "مجتمع BYD في الأردن",
    platform: "telegram",
    url: "https://t.me/BYD_EV_Club_Jordan",
    members: "4,300+",
    region: "Jordan",
  },
  {
    id: "byd-autovehicle",
    name: "BYD AutoVehicle Group",
    nameAr: "مجموعة BYD للسيارات",
    description: "General BYD discussion group",
    descriptionAr: "مجموعة نقاش عامة لـ BYD",
    platform: "telegram",
    url: "https://t.me/BYDautoVehicle",
    region: "Global",
  },
  {
    id: "cars-by-maged",
    name: "Cars by Maged",
    nameAr: "Cars by Maged",
    description: "Egyptian car reviewer — EV reviews & range tests (Arabic)",
    descriptionAr: "مراجع سيارات مصري — مراجعات EV واختبارات المدى",
    platform: "youtube",
    url: "https://www.youtube.com/@carsbymaged",
    region: "Egypt",
  },
  {
    id: "xda-byd",
    name: "XDA — BYD Multimedia",
    nameAr: "XDA — وسائط BYD",
    description: "Technical discussion for BYD head unit modifications",
    descriptionAr: "نقاش تقني لتعديلات وحدة رأس BYD",
    platform: "forum",
    url: "https://xdaforums.com/t/byd-multimedia-install-apk.4541247/",
    region: "Global",
  },
  {
    id: "byd-egypt-official",
    name: "BYD Egypt Official",
    nameAr: "BYD مصر الرسمي",
    description: "Official BYD Egypt website",
    descriptionAr: "الموقع الرسمي لـ BYD مصر",
    platform: "website",
    url: "https://www.byd.com/en-eg",
    region: "Egypt",
  },
  {
    id: "byd-egypt-dealer",
    name: "BYD Egypt Dealer",
    nameAr: "وكيل BYD مصر",
    description: "BYD Egypt dealer & service information",
    descriptionAr: "معلومات الوكيل والخدمة",
    platform: "website",
    url: "https://bydegypt.com",
    region: "Egypt",
  },
  {
    id: "ellamotors-byd",
    name: "Ella Motors — BYD Egypt",
    nameAr: "إيلا موتورز — BYD مصر",
    description: "BYD prices, specs and features in Egypt",
    descriptionAr: "أسعار ومواصفات BYD في مصر",
    platform: "website",
    url: "https://egypt.ellamotors.com/new-cars/byd",
    region: "Egypt",
  },
  {
    id: "electriccar-byd",
    name: "ElectricCar-BYD",
    nameAr: "ElectricCar-BYD",
    description: "Community hub for BYD owners — manuals and news",
    descriptionAr: "مركز مجتمع لملاك BYD — أدلة وأخبار",
    platform: "website",
    url: "https://electriccar-byd.com/en",
    region: "Global",
  },
];

// ---------------------------------------------------------------------------
// Documentation
// ---------------------------------------------------------------------------
export interface DocLink {
  id: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  type: "manual" | "guide" | "repair" | "technical";
  url: string;
  models?: CarModelId[];
}

export const documentationLinks: DocLink[] = [
  {
    id: "byd-manuals",
    name: "BYD Owner Manuals (all models)",
    nameAr: "أدلة مالك BYD",
    description: "Official owner manuals — Seal, Dolphin, Atto 3, Han, Tang, Song",
    descriptionAr: "أدلة المالك الرسمية لجميع الموديلات",
    type: "manual",
    url: "https://electriccar-byd.com/en/manual",
    models: ALL_MODELS,
  },
  {
    id: "han-manual-pdf",
    name: "BYD Han Owner Manual (PDF)",
    nameAr: "دليل مالك BYD هان",
    description: "Left-hand drive Han owner manual (English, 2024)",
    descriptionAr: "دليل مالك هان بالإنجليزية 2024",
    type: "manual",
    url: "https://www.bydqatar.com.qa/wp-content/uploads/2025/01/BYD-HAN-Owners-Manual-Left-hand-Drive-EN-240902-compressed.pdf",
    models: ["han"],
  },
  {
    id: "atto3-yandex",
    name: "Atto 3 / Yuan Plus Manual (EN)",
    nameAr: "دليل أتو 3 / يوان بلس",
    description: "Full English manual for Atto 3 / Yuan Plus (2022)",
    descriptionAr: "دليل كامل لـ أتو 3 / يوان بلس",
    type: "manual",
    url: y("Documentation/BYD ATTO 3 = Yuan Plus (EN, 2022).pdf"),
    models: ["atto3"],
  },
  {
    id: "seal-manual",
    name: "BYD Seal Manual",
    nameAr: "دليل BYD سيل",
    description: "Seal owner manual (Russian & English versions)",
    descriptionAr: "دليل مالك سيل",
    type: "manual",
    url: y("Documentation/BYD Seal (RU, 2022).pdf"),
    models: ["seal"],
  },
  {
    id: "tang-manual",
    name: "BYD Tang User Manual (2021)",
    nameAr: "دليل BYD تانج 2021",
    description: "Tang 2021 English owner manual",
    descriptionAr: "دليل مالك تانج 2021 بالإنجليزية",
    type: "manual",
    url: y("Documentation/BYD TANG 2021 User Manual.pdf"),
    models: ["tang"],
  },
  {
    id: "tang-service",
    name: "BYD Tang EV — Service Manual",
    nameAr: "دليل صيانة تانج EV",
    description: "Dealer-level service manual for Tang EV",
    descriptionAr: "دليل صيانة تانج EV بمستوى الوكيل",
    type: "repair",
    url: y("Documentation/BYD TANG EV Service Manual.pdf"),
    models: ["tang"],
  },
  {
    id: "song-plus-manual",
    name: "BYD Song Plus EV 2023 Manual",
    nameAr: "دليل سونج بلس 2023",
    description: "Champion Edition manual (Russian)",
    descriptionAr: "دليل نسخة الشامبيون (روسي)",
    type: "manual",
    url: y("Documentation/BYD Song Plus EV2023 Champion Edition user manual (RU).pdf"),
    models: ["song-plus"],
  },
  {
    id: "dolphin-manual",
    name: "BYD Dolphin Manual (CN)",
    nameAr: "دليل BYD دولفين",
    description: "Dolphin owner manual (Chinese)",
    descriptionAr: "دليل مالك دولفين (صيني)",
    type: "manual",
    url: y("Documentation/BYD Dolphin (CN, 2022).pdf"),
    models: ["dolphin"],
  },
  {
    id: "repair-manuals",
    name: "BYD Repair Manuals Repo (GitHub)",
    nameAr: "مستودع أدلة إصلاح BYD",
    description: "Repair manuals & factory images repository",
    descriptionAr: "أدلة الإصلاح وصور المصنع",
    type: "repair",
    url: "https://github.com/BYDcar/BYDRepairManual",
  },
  {
    id: "wiring-diagrams",
    name: "Wiring Diagrams & Power Distribution",
    nameAr: "مخططات الأسلاك وتوزيع الطاقة",
    description: "Dashboard, front and rear power distribution diagrams",
    descriptionAr: "مخططات توزيع الطاقة",
    type: "technical",
    url: y("Documentation/Wiring Diagrams"),
  },
  {
    id: "firmware-github",
    name: "BYD Firmware Repository (GitHub)",
    nameAr: "مستودع البرامج الثابتة",
    description: "Complete firmware collection organized by chip and model",
    descriptionAr: "مجموعة كاملة من البرامج الثابتة",
    type: "technical",
    url: "https://github.com/BYDcar",
  },
  {
    id: "anexplorer-byd",
    name: "AnExplorer — BYD Guide",
    nameAr: "دليل AnExplorer لـ BYD",
    description: "File manager installation guide for BYD Android Automotive",
    descriptionAr: "دليل تثبيت مدير الملفات لسيارات BYD",
    type: "guide",
    url: "https://anexplorer.io/device/android-automotive/byd",
    models: ["seal", "dolphin", "atto3"],
  },
  {
    id: "flashing-guide",
    name: "Firmware Flashing Guide",
    nameAr: "دليل تحديث البرنامج الثابت",
    description: "Step-by-step guide for flashing BYD firmware via USB",
    descriptionAr: "دليل خطوة بخطوة لتحديث البرنامج عبر USB",
    type: "guide",
    url: "https://github.com/BYDcar/BYDGlobalFactoryImages1/blob/main/README.md",
  },
];

// ---------------------------------------------------------------------------
// Guides
// ---------------------------------------------------------------------------
export interface Guide {
  id: string;
  title: string;
  titleAr: string;
  description: string;
  descriptionAr: string;
  steps: string[];
  stepsAr: string[];
  warning?: string;
  warningAr?: string;
}

export const guides: Guide[] = [
  {
    id: "microg-install",
    title: "Installing microG Services",
    titleAr: "تثبيت خدمات microG",
    description: "Required for YouTube ReVanced and other modified apps",
    descriptionAr: "مطلوب لـ YouTube ReVanced والتطبيقات المعدلة الأخرى",
    steps: [
      "Remove any previous microG / Gbox install and clear residues with SD Maid SE",
      "Install microG GmsCore from the official GitHub release",
      "Install microG Companion",
      "Grant all permissions: Settings > Apps > microG Services",
      "Set Location to 'Always Allow' and enable Overlay permission",
      "Repeat permission grants for microG Companion",
    ],
    stepsAr: [
      "احذف أي تثبيت سابق لـ microG ونظّف البقايا بواسطة SD Maid SE",
      "قم بتثبيت microG GmsCore من GitHub",
      "قم بتثبيت microG Companion",
      "امنح جميع الأذونات: الإعدادات > التطبيقات > microG Services",
      "اضبط الموقع على 'السماح دائماً' وفعّل إذن التراكب",
      "كرر نفس الأذونات لـ microG Companion",
    ],
    warning: "Do not use Phone Clone or any transfer utility — fresh install only",
    warningAr: "لا تستخدم Phone Clone — تثبيت جديد فقط",
  },
  {
    id: "silentinstaller",
    title: "Silent Installer for Leopard / Denza",
    titleAr: "Silent Installer لـ ليوبارد / دينزا",
    description: "Install APKs silently via USB drive",
    descriptionAr: "تثبيت التطبيقات بصمت عبر USB",
    steps: [
      "Download SilentInstaller.zip from the Yandex drive",
      "Extract the zip file",
      "Format a USB drive as FAT32",
      "Copy the extracted files to the root of the USB drive",
      "Plug the USB into your BYD Leopard or Denza",
      "Installation starts automatically",
    ],
    stepsAr: [
      "قم بتحميل SilentInstaller.zip من ياندكس",
      "قم بفك ضغط الملف",
      "قم بتهيئة USB بتنسيق FAT32",
      "انسخ الملفات المستخرجة إلى جذر USB",
      "قم بتوصيل USB بسيارتك",
      "سيبدأ التثبيت تلقائياً",
    ],
    warning: "Only for BYD Leopard and Denza models",
    warningAr: "فقط لموديلات ليوبارد ودينزا",
  },
  {
    id: "firmware-flash",
    title: "Flashing Stock Firmware via USB",
    titleAr: "تحديث البرنامج الثابت عبر USB",
    description: "Restore or update your BYD head unit firmware",
    descriptionAr: "استعادة أو تحديث برنامج وحدة الرأس",
    steps: [
      "Download the firmware zip for your Dilink version from the Firmware section",
      "Rename the file to UpdateFull.zip",
      "Format a USB drive as FAT32",
      "Create folder structure: BYDUpdatePackage/msm8953_64/",
      "Copy UpdateFull.zip to the created folder",
      "Plug USB into the car data port while the system is running",
      "Wait for automatic recognition and update (~10 min)",
      "System restarts automatically when complete",
    ],
    stepsAr: [
      "قم بتحميل ملف البرنامج الثابت لـ Dilink الخاص بك",
      "أعد تسمية الملف إلى UpdateFull.zip",
      "قم بتهيئة USB بتنسيق FAT32",
      "أنشئ المسار: BYDUpdatePackage/msm8953_64/",
      "انسخ UpdateFull.zip إلى المجلد",
      "قم بتوصيل USB بمنفذ البيانات والسيارة تعمل",
      "انتظر التحديث التلقائي (~10 دقائق)",
      "سيعيد النظام التشغيل تلقائياً عند الانتهاء",
    ],
    warning: "Alternative: long press 'Previous' + 'Volume wheel' to enter engineering mode",
    warningAr: "طريقة بديلة: اضغط مطولاً على 'السابق' + 'عجلة الصوت' للدخول لوضع الهندسة",
  },
];

// ---------------------------------------------------------------------------
// Navigation items — no 'Car Models' per spec
// ---------------------------------------------------------------------------
export const navItems = [
  { id: "apps", name: "Apps", nameAr: "التطبيقات", href: "#apps" },
  { id: "firmware", name: "Firmware", nameAr: "البرامج الثابتة", href: "#firmware" },
  { id: "guides", name: "Guides", nameAr: "الأدلة", href: "#guides" },
  { id: "docs", name: "Documentation", nameAr: "التوثيق", href: "#documentation" },
  { id: "community", name: "Community", nameAr: "المجتمع", href: "#community" },
] as const;
